buku/urls.py
from django.urls import path
from . import views

app_name = 'buku'
urlpatterns = [
    path('', views.index),
    path('delete/<int:buku_id>', views.delete, name="delete"),
    path('edit/<int:buku_id>', views.edit, name="edit")
]

perpus/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('buku/', include('buku.urls', namespace="buku")),
]

buku/models.py
from django.db import models

class Buku(models.Model):
    judul = models.CharField(max_length=30)
    sinopsis = models.TextField()
    author = models.CharField(max_length=20)

    def __str__(self):
        return "{}".format(self.judul)

buku/forms.py
from django.forms import ModelForm
from .models import Buku

class BukuForm(ModelForm):
    class Meta:
        model = Buku
        fields = [
            'judul',
            'sinopsis',
            'author',
        ]

buku/views.py
from django.shortcuts import render, redirect
from .forms import BukuForm
from .models import Buku

def index(request):
    buku_form = BukuForm(request.POST or None)
    if request.method == "POST":
        if buku_form.is_valid():
            buku_form.save()

            return redirect("/")
        else:
            pass
    else:
        pass

    context = {
        'title': 'Tambah Buku',
        'buku_form': buku_form,
    }
    return render(request, 'buku/index.html', context)

def edit(request, buku_id):
    update_buku = Buku.objects.get(id=buku_id)
    newData = {
        'judul': update_buku.judul,
        'sinopsis': update_buku.sinopsis,
        'author': update_buku.author,
    }
    buku_form = BukuForm(request.POST or None, instance=update_buku)
    if request.method == "POST":
        if buku_form.is_valid():
            buku_form.save()

            return redirect("/")
        else:
            pass
    else:
        pass

    context = {
        'title': 'Edit Buku',
        'buku_form': buku_form,
    }
    return render(request, 'buku/index.html', context)

def delete(request, buku_id):
    buku = Buku.objects.filter(id=buku_id)
    buku.delete()

    return redirect("/")

perpus/views.py
from django.shortcuts import render
from buku.models import Buku

def index(request):
    buku = Buku.objects.all()
    context = { 'buku': buku }
    return render(request, 'index.html', context)

buku/templates/buku/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{ title }}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <div class="container">
      <h1>{{ title }}</h1>
      <a href="/" class="btn btn-danger">List Buku</a>
      <hr />
      <form method="POST">
        {% csrf_token %}
        <table>
          {{ buku_form }}
        </table>
        <button type="Submit" class="btn btn-primary">Buat</button>
      </form>
    </div>
  </body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Perpus App</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <div class="container">
      <h1>Perpus App</h1>
      <hr />
      <a class="btn btn-primary" href="/buku">Tambah buku</a>

      <table class="table">
        <thead>
          <tr>
            <th scope="col">No</th>
            <th scope="col">Judul</th>
            <th scope="col">Sinopsis</th>
            <th scope="col">Author</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          {% for item in buku %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ item.judul }}</td>
            <td>{{ item.sinopsis }}</td>
            <td>{{ item.author }}</td>
            <td>
              <a class="btn btn-warning" href="{% url 'buku:edit' item.id %}"
                >Edit</a
              >
              <a class="btn btn-danger" href="{% url 'buku:delete' item.id %}"
                >Delete</a
              >
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </body>
</html>